"""Constants package for the Archer secret validation system.

This package contains constant definitions organized by domain.
"""

# Template-related constants
from .template import (
    MODE_SINGLE,
    MODE_MULTIPART,
    DEFAULT_TEMPLATES_DIR,
    TEMPLATE_FILE_EXTENSION,
    TEMPLATE_FILE_EXTENSIONS,
    VARIABLE_PATTERN,
    SECRET_VARIABLE_NAME,
    UPPER_SNAKE_CASE_PATTERN,
    KEBAB_CASE_PATTERN,
)

# HTTP-related constants
from .http import (
    METHOD_GET,
    DEFAULT_TIMEOUT,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
)

# CLI-related constants
from .cli import (
    SUCCESS_INDICATOR,
    FAILURE_INDICATOR,
    OPT_VAR,
)

# Validation-related constants
from .validation import (
    VARIABLE_SEPARATOR,
    VARIABLE_SEPARATOR_COUNT,
    KEBAB_TO_SNAKE_SEPARATOR,
    SNAKE_CASE_SEPARATOR,
)

# Security-related constants
from .security import (
    MASKED_VARIABLE_FORMAT,
    MASKED_VARIABLE_PREFIX,
    MASKED_VARIABLE_SUFFIX,
)

# File system-related constants
from .filesystem import (
    ENCODING_UTF8,
    READ_MODE,
)

# Package constants
from .package import (
    VERSION,
)

# Logging constants
from .logging import (
    DEFAULT_LOG_FORMAT,
    TIME_FORMAT,
    VALIDATOR_INITIALIZED,
    TEMPLATE_LOADER_INITIALIZED,
    VALIDATION_STARTED,
    VALIDATION_SUCCESS,
    VALIDATION_FAILED,
    REQUEST_PREPARING,
    REQUEST_SENDING,
    REQUEST_COMPLETED,
    REQUEST_TIMEOUT_LOG,
    REQUEST_FAILED_LOG,
    TEMPLATE_LOADED,
    VARIABLE_NOT_FOUND,
)

# Message constants
from .messages import (
    SECRET_VALID,
    TEMPLATE_NOT_FOUND,
    REQUEST_TIMEOUT,
    REQUEST_FAILED,
    INVALID_JSON_RESPONSE,
    REQUIRED_FIELD_NOT_FOUND,
    MODE_VALIDATION_ERROR,
    MULTIPART_REQUIRES_VARIABLES,
    SINGLE_MODE_NO_VARIABLES,
    MUTUAL_EXCLUSION_ERROR,
    UPPER_SNAKE_CASE_ERROR,
    SECRET_NOT_ALLOWED_MULTIPART,
    INVALID_VARIABLES_SINGLE,
    UNDEFINED_VARIABLES,
    UNUSED_REQUIRED_VARIABLES,
    MISSING_REQUIRED_VARIABLES,
    UNEXPECTED_VARIABLES,
    INVALID_VARIABLE_FORMAT,
    INVALID_KEBAB_CASE,
)

__all__ = [
    # Template constants
    'MODE_SINGLE',
    'MODE_MULTIPART',
    'DEFAULT_TEMPLATES_DIR',
    'TEMPLATE_FILE_EXTENSION',
    'TEMPLATE_FILE_EXTENSIONS',
    'VARIABLE_PATTERN',
    'SECRET_VARIABLE_NAME',
    'UPPER_SNAKE_CASE_PATTERN',
    'KEBAB_CASE_PATTERN',

    # HTTP constants
    'METHOD_GET',
    'DEFAULT_TIMEOUT',
    'DEFAULT_MAX_RETRIES',
    'DEFAULT_RETRY_DELAY',

    # CLI constants
    'SUCCESS_INDICATOR',
    'FAILURE_INDICATOR',
    'OPT_VAR',

    # Validation constants
    'VARIABLE_SEPARATOR',
    'VARIABLE_SEPARATOR_COUNT',
    'KEBAB_TO_SNAKE_SEPARATOR',
    'SNAKE_CASE_SEPARATOR',

    # Security constants
    'MASKED_VARIABLE_FORMAT',
    'MASKED_VARIABLE_PREFIX',
    'MASKED_VARIABLE_SUFFIX',

    # Filesystem constants
    'ENCODING_UTF8',
    'READ_MODE',

    # Package constants
    'VERSION',

    # Logging constants
    'DEFAULT_LOG_FORMAT',
    'TIME_FORMAT',
    'VALIDATOR_INITIALIZED',
    'TEMPLATE_LOADER_INITIALIZED',
    'VALIDATION_STARTED',
    'VALIDATION_SUCCESS',
    'VALIDATION_FAILED',
    'REQUEST_PREPARING',
    'REQUEST_SENDING',
    'REQUEST_COMPLETED',
    'REQUEST_TIMEOUT_LOG',
    'REQUEST_FAILED_LOG',
    'TEMPLATE_LOADED',
    'VARIABLE_NOT_FOUND',

    # Message constants
    'SECRET_VALID',
    'TEMPLATE_NOT_FOUND',
    'REQUEST_TIMEOUT',
    'REQUEST_FAILED',
    'INVALID_JSON_RESPONSE',
    'REQUIRED_FIELD_NOT_FOUND',
    'MODE_VALIDATION_ERROR',
    'MULTIPART_REQUIRES_VARIABLES',
    'SINGLE_MODE_NO_VARIABLES',
    'MUTUAL_EXCLUSION_ERROR',
    'UPPER_SNAKE_CASE_ERROR',
    'SECRET_NOT_ALLOWED_MULTIPART',
    'INVALID_VARIABLES_SINGLE',
    'UNDEFINED_VARIABLES',
    'UNUSED_REQUIRED_VARIABLES',
    'MISSING_REQUIRED_VARIABLES',
    'UNEXPECTED_VARIABLES',
    'INVALID_VARIABLE_FORMAT',
    'INVALID_KEBAB_CASE',
]
